"""add watch links

Revision ID: 7962bc10e3b5
Revises: 78d5d48692ac
Create Date: 2026-03-28 22:19:17.525102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7962bc10e3b5'
down_revision = '78d5d48692ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watch_links', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('watch_links')

    # ### end Alembic commands ###
